act_comm.o: act_comm.c merc.h config.h handler.h
act_info.o: act_info.c merc.h config.h update.h interp.h
act_move.o: act_move.c merc.h config.h handler.h
act_obj.o: act_obj.c merc.h config.h mp_wyzw.h magic.h handler.h
act_wiz.o: act_wiz.c merc.h config.h special.h mp_wyzw.h interp.h \
 handler.h
clan.o: clan.c merc.h config.h
comm.o: comm.c merc.h config.h update.h
const.o: const.c merc.h config.h
db.o: db.c merc.h config.h ssm.h handler.h
fight.o: fight.c merc.h config.h update.h handler.h
gry.o: gry.c merc.h config.h
handler.o: handler.c merc.h config.h update.h mp_pol.h handler.h
httpd.o: httpd.c merc.h config.h interp.h
hunt.o: hunt.c merc.h config.h
interp.o: interp.c merc.h config.h interp.h
kzapisz.o: kzapisz.c merc.h config.h kzapisz.h
lac.o: lac.c merc.h config.h
lanclicz.o: lanclicz.c merc.h config.h
magic.o: magic.c merc.h config.h magic.h handler.h
mp_pol.o: mp_pol.c merc.h config.h mp_wyzw.h mp_pol.h magic.h handler.h
mp_wczyt.o: mp_wczyt.c merc.h config.h mp_wczyt.h mp_pol.h
mp_wyr.o: mp_wyr.c merc.h config.h
mp_wyzw.o: mp_wyzw.c merc.h config.h mp_wyzw.h
nanny.o: nanny.c merc.h config.h
necro.o: necro.c merc.h config.h magic.h handler.h
palad.o: palad.c merc.h config.h handler.h
qmagic.o: qmagic.c merc.h config.h magic.h handler.h
save.o: save.c merc.h config.h
screen.o: screen.c merc.h config.h
skr.o: skr.c merc.h config.h handler.h
socjalne.o: socjalne.c merc.h config.h
special.o: special.c merc.h config.h special.h
ssm.o: ssm.c merc.h config.h ssm.h
um_ras.o: um_ras.c merc.h config.h
update.o: update.c merc.h config.h update.h mp_pol.h handler.h
gla/combo.o: gla/combo.c gla/glaca.h merc.h config.h
gla/glaca.o: gla/glaca.c gla/glaca.h merc.h config.h mp_wczyt.h
gla/kraina.o: gla/kraina.c gla/glaca.h merc.h config.h kzapisz.h
gla/lpl.o: gla/lpl.c gla/glaca.h merc.h config.h
gla/mapa.o: gla/mapa.c gla/glaca.h merc.h config.h
gla/mob.o: gla/mob.c gla/glaca.h merc.h config.h special.h handler.h
gla/pomieszczenie.o: gla/pomieszczenie.c gla/glaca.h merc.h config.h handler.h
gla/progi.o: gla/progi.c gla/glaca.h merc.h config.h mp_wczyt.h
gla/przedmiot.o: gla/przedmiot.c gla/glaca.h merc.h config.h handler.h
gla/reset.o: gla/reset.c gla/glaca.h merc.h config.h kzapisz.h
gla/vnum.o: gla/vnum.c gla/glaca.h merc.h config.h
gla/wyjscie.o: gla/wyjscie.c gla/glaca.h merc.h config.h handler.h
